---
title: "test2computers"
author: "Matthew McHugh"
date: "5/9/2019"
output: html_document
---
I added this from penn to test if on laptop
now added this too...
Now I am making a change on the laptop
Now I am making a change again on penn
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Do this once per new project.
Go to https://github.com and make sure you are logged in.
Click green “New repository” button. Or, if you are on your own profile page, click on “Repositories”, then click the green “New” button.
Repository name: myrepo (or whatever you wish)
Public
YES Initialize this repository with a README
Click the big green button “Create repository.”
Copy the HTTPS clone URL to your clipboard via the green “Clone or Download” button. Or copy the SSH URL if you chose to set up SSH keys.

THEN ON SECOND COMPUTER
Open RStudio
Start a new project under version contrl
Copy repository URL
create as subdirectory (same name)
do a pull to bring everything into 2nd computer

From then on, whenever you start working on the project, always pull first